### ISSUE TITLE
Please add english language

### ISSUE THREAD

**Issue by nOLanSea** [kLauncher/kLauncher#1]
Hello! Foreign starcraft community noticed some korean players using KLauncher.
Is it possible to add english language please ? Thanks

**Comment by alexhanbich** [comment]
I can translate the README if that helps

**Comment by somersby10ml** [comment]
> I can translate the README if that helps

If you send a PR after translation, we will reflect it.

**Comment by tobeinged** [comment]
Yes, we non_korean players need a english language,or at least a User Guide txt file In English,
Please take some time to translate it, thank you!
