### ISSUE TITLE
It show me a new version Even after i have updated to the lastest version

### ISSUE THREAD

**Issue by tobeinged** [kLauncher/kLauncher#5]
i have update it to 3.3.8  when date 2023.3.14
but when date 3.15  3.16 
when i run klauncher, after login, it shows a dos window,says a new version.
i am not korean,i use some translate tools to use it.
is there someings i set wrong? or is it t bug?

on more thing, when i enter the game room, it shows others game record right,but my game record is 0-0-0
somebody show me how to use this launcher right?
thanks ,love you, guys!

**Comment by somersby10ml** [comment]
discord ㅁㄱㄱ#3708
